docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - v3:
        - Introduction: v3/intro.md
        - Installation: v3/installation.md
        - "Quick Start": v3/quick-start.md
        - "PSR-11 Support": v3/psr-11.md
        - Configuration: v3/config.md
        - "Injector": v3/injector.md
        - "Code Generator": v3/codegen.md
        - Cookbook:
            - "Usage with PSR-11 Containers": v3/cookbook/use-with-psr-containers.md
            - "Usage with laminas-servicemanager": v3/cookbook/use-with-servicemanager.md
            - "Using AoT with Mezzio and laminas-servicemanager": v3/cookbook/aot-guide.md
        - Migration:
            - "Migration from Version 2 to 3": v3/migration.md
    - v2:
        - "Quick Start": v2/quick-start.md
        - Reference:
            - "Dependency Definitions": v2/definitions.md
            - "Instance Manager": v2/instance-manager.md
            - Configuration: v2/config.md
            - "Debugging And Complex Use Cases": v2/debugging-and-complex-use-cases.md

site_name: laminas-di
site_description: "Automated dependency injection for PSR-11 containers"
repo_url: 'https://github.com/laminas/laminas-di'
extra:
    project: Components
    current_version: v3
    versions:
        - v3
        - v2
    installation:
        config_provider_class: 'Laminas\Di\ConfigProvider'
        module_class: 'Laminas\Di\Module'
